// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Data$ReasonMedellinjs = require("./Data.bs.js");

function AppSolucion(Props) {
  var match = Data$ReasonMedellinjs.personOne[/* edad */2];
  return React.createElement("div", undefined, React.createElement("p", undefined, Data$ReasonMedellinjs.personOne[/* nombre */0]), React.createElement("p", undefined, Data$ReasonMedellinjs.personOne[/* apellido */1]), React.createElement("p", undefined, match !== undefined ? String(match) : "No tiene edad"));
}

var make = AppSolucion;

exports.make = make;
/* react Not a pure module */
