// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var personOne = /* record */[
  /* nombre */"tu nombre",
  /* apellido */"tu apellido",
  /* edad */32
];

var personTwo = /* record */[
  /* nombre */"John",
  /* apellido */"Doe",
  /* edad */undefined
];

var personThree = /* record */[
  /* nombre */"Jane",
  /* apellido */"Doe",
  /* edad */undefined
];

var people_001 = /* :: */[
  personTwo,
  /* :: */[
    personThree,
    /* [] */0
  ]
];

var people = /* :: */[
  personOne,
  people_001
];

var peopleWithAge = Belt_List.keep(people, (function (person) {
        return Belt_Option.isSome(person[/* edad */2]);
      }));

var peopleWithoutAge = Belt_List.keep(people, (function (person) {
        return Belt_Option.isNone(person[/* edad */2]);
      }));

exports.personOne = personOne;
exports.personTwo = personTwo;
exports.personThree = personThree;
exports.people = people;
exports.peopleWithAge = peopleWithAge;
exports.peopleWithoutAge = peopleWithoutAge;
/* peopleWithAge Not a pure module */
