// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var App$ReasonMedellinjs = require("./App.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(App$ReasonMedellinjs.make, { }), "app");

/*  Not a pure module */
