// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var $$String = require("bs-platform/lib/js/string.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");

var personOne = /* record */[
  /* nombre */"tu nombre",
  /* apellido */"tu apellido",
  /* edad */32
];

var personTwo = /* record */[
  /* nombre */"John",
  /* apellido */"Doe",
  /* edad */undefined
];

var personThree = /* record */[
  /* nombre */"Jane",
  /* apellido */"Doe",
  /* edad */undefined
];

var people_001 = /* :: */[
  personTwo,
  /* :: */[
    personThree,
    /* [] */0
  ]
];

var people = /* :: */[
  personOne,
  people_001
];

Belt_List.forEach(people, (function (person) {
        var nombreCompleto = person[/* nombre */0] + (" " + person[/* apellido */1]);
        var match = person[/* edad */2];
        var edad = match !== undefined ? "(" + (String(match) + ")") : "";
        console.log(nombreCompleto + (edad + "\n"));
        return /* () */0;
      }));

function getFullName(person) {
  var match = person[/* edad */2];
  if (match !== undefined) {
    return person[/* nombre */0] + (" " + (person[/* apellido */1] + ("(" + (String(match) + ")"))));
  } else {
    return person[/* nombre */0] + (" " + person[/* apellido */1]);
  }
}

Belt_List.forEach(people, (function (person) {
        console.log(getFullName(person) + "\n");
        return /* () */0;
      }));

Belt_List.forEach(Belt_List.map(Belt_List.map(people, getFullName), $$String.uppercase), (function (prim) {
        console.log(prim);
        return /* () */0;
      }));

exports.personOne = personOne;
exports.personTwo = personTwo;
exports.personThree = personThree;
exports.people = people;
exports.getFullName = getFullName;
/*  Not a pure module */
